name: Set Build Role
description: Sets the required build role which is needed for the provided environment infrastructure
inputs:
  prod-role:
    description: Production Build Role 
    required: true
  dev-role:
    description: Dev Build Role
    required: true
  stage-role:
    description: Stage Build Role
    required: true
  environment-name:
    description: The target environment name
    required: true
outputs:
  build-role:
    description: The build role applicable to the provided environment
runs:
  using: 'node12'
  main: 'dist/index.js'